### ISSUE TITLE
Token Registry Update Request: DevNet - Cosmos Hub

### ISSUE THREAD

**Issue by timlind** [Sifchain/sifnode#1763]
Requested update: 
```
connection-id: connection-110
channel-id: channel-110
counterparty-channel-id: channel-3
```

Request / source of truth from chainops / relayer

```
sifnoded q ibc channel channels --node tcp://rpc-devnet.sifchain.finance:80 | grep 'connection-110' -A 5 -B 5
  port_id: transfer
  state: STATE_INIT
  version: ics20-1
- channel_id: channel-101
  connection_hops:
  - connection-110
  counterparty:
    channel_id: channel-3
    port_id: transfer
  ordering: ORDER_UNORDERED
  port_id: transfer
```

Entry before updating:

```
{
      "is_whitelisted": true,
      "decimals": "6",
      "denom": "ibc/C782C1DE5F380BC8A5B7D490684894B439D31847A004B271D7B7BA07751E582A",
      "base_denom": "uphoton",
      "path": "transfer/channel-101",
      "src_channel": "channel-101",
      "dest_channel": "channel-3",
      "display_name": "uPHOTON",
      "display_symbol": "",
      "network": "",
      "address": "",
      "external_symbol": "uPHOTON",
      "transfer_limit": "",
      "permissions": [
        "CLP",
        "IBCEXPORT",
        "IBCIMPORT"
      ]
    }
```

New entry:

```
 {
      "is_whitelisted": true,
      "decimals": "6",
      "denom": "ibc/C782C1DE5F380BC8A5B7D490684894B439D31847A004B271D7B7BA07751E582A",
      "base_denom": "uphoton",
      "path": "transfer/channel-101",
      "src_channel": "channel-101",
      "dest_channel": "channel-3",
      "display_name": "",
      "display_symbol": "",
      "network": "",
      "address": "",
      "external_symbol": "",
      "transfer_limit": "",
      "permissions": [
        "CLP",
        "IBCEXPORT",
        "IBCIMPORT"
      ]
    }
```

Done
```
~ % sifnoded tx tokenregistry register uphoton-devnet.json --node http://rpc-devnet.sifchain.finance:80 --chain-id sifchain-devnet-1 --from tokenwhitelister --keyring-backend test --gas-prices=0.5rowan --gas-adjustment=1.5                                                             
{"body":{"messages":[{"@type":"/sifnode.tokenregistry.v1.MsgRegister","from":"sif1tpypxpppcf5lea47vcvgy09675nllmcucxydvu","entry":{"is_whitelisted":true,"decimals":"6","denom":"ibc/C782C1DE5F380BC8A5B7D490684894B439D31847A004B271D7B7BA07751E582A","base_denom":"uphoton","path":"transfer/channel-101","src_channel":"channel-101","dest_channel":"channel-3","display_name":"","display_symbol":"","network":"","address":"","external_symbol":"","transfer_limit":"","permissions":["CLP","IBCEXPORT","IBCIMPORT"]}}],"memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[{"denom":"rowan","amount":"100000"}],"gas_limit":"200000","payer":"","granter":""}},"signatures":[]}

confirm transaction before signing and broadcasting [y/N]: y
{"height":"1776967","txhash":"D5B31E92A1D956037D8B96F608804ABE0182A32A0E83FD942ACF857448F1B9CE","codespace":"","code":0,"data":"0A0A0A087265676973746572","raw_log":"[{\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"register\"}]}]}]","logs":[{"msg_index":0,"log":"","events":[{"type":"message","attributes":[{"key":"action","value":"register"}]}]}],"info":"","gas_wanted":"200000","gas_used":"115088","tx":null,"timestamp":""}
```
