### ISSUE TITLE
Not able to transfer eth asset (ibc denom) from cosmos to sif

### ISSUE THREAD

**Issue by pgoos** [Sifchain/sifnode#1846]
**Current behavior**
Eth assets are not transferred from cosmos to sif and no refund is performed. Balance is deducted on the cosmos side but not updated on sif side. After timeout has reached, funds are not given back

**Expected behavior**
IBC denom assets are transferred from cosmos to sif. Balance is deducted on the cosmos side and is updated accordingly on the sif side.

**Steps to reproduce**
1.  Query balance on the cosmos test network

> gaiad query bank balances cosmos19q2swhcxkxlc6va3pz5jz42jfsfv2ly4npn3ty --node https://rpc.testnet.cosmos.network:443 --chain-id cosmoshub-testnet
```
balances:
- amount: "1000000000000"
  denom: ibc/11C219BAA2C8AF0862D6F77F1BD62DE59755D5EAAF3B33FE0CEAFADD2195328E
- amount: "500"
  denom: ibc/7E10CAD296837763B61CD8376EE9B1AD526FFF42BD61E99D1149F68CF044F6C5
- amount: "20000000000"
  denom: ibc/830D5C093E8D24CE25C1BFF5896B382589E07E37C316684F661A24E74B00B9A8
- amount: "30814542915"
  denom: ibc/EAB7F58822348DDDA139B53062229470220170D7376FAAC5CEACD65BDA3347FA
- amount: "100"
  denom: ibc/FEB745594AA528DDB2EB216943D81DB046308A47C07ACB96D58AB4D7B067EC1C
- amount: "989777777778"
  denom: uphoton
```

Note
```  
denom: ibc/830D5C093E8D24CE25C1BFF5896B382589E07E37C316684F661A24E74B00B9A8
- amount: "30814542915"
```

2. Query the balance on the sif side (DevNet):
> sifnoded query bank balances sif19q2swhcxkxlc6va3pz5jz42jfsfv2ly4kuu8y0 --> node=tcp://rpc-devnet.sifchain.finance:80 --chain-id=sifchain-devnet-1 | grep eth -B 1
```
- amount: "7706325658500000000"
  denom: ceth
--
- amount: "0"
  denom: xeth`
```
3. Transfer funds from cosmos test network to our DevNet with `gaiad` CLI

> gaiad     tx     ibc-transfer     transfer     transfer     channel-26     sif19q2swhcxkxlc6va3pz5jz42jfsfv2ly4kuu8y0     2000000000ibc/EAB7F58822348DDDA139B53062229470220170D7376FAAC5CEACD65BDA3347FA     --from cosmos19q2swhcxkxlc6va3pz5jz42jfsfv2ly4npn3ty     --keyring-backend test     --chain-id cosmoshub-testnet     --node https://rpc.testnet.cosmos.network:443 -y --gas-prices 2.0uphoton --gas 300000 --packet-timeout-timestamp 600000000000

```
{"height":"361911","txhash":"2E8DDBD965ED8C48B88AA15F7E42A2BA434F64984D692D0C6B7843127970DDA1","codespace":"","code":0,"data":"0A0A0A087472616E73666572","raw_log":"[{\"events\":[{\"type\":\"ibc_transfer\",\"attributes\":[{\"key\":\"sender\",\"value\":\"cosmos19q2swhcxkxlc6va3pz5jz42jfsfv2ly4npn3ty\"},{\"key\":\"receiver\",\"value\":\"sif19q2swhcxkxlc6va3pz5jz42jfsfv2ly4kuu8y0\"}]},{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"transfer\"},{\"key\":\"sender\",\"value\":\"cosmos19q2swhcxkxlc6va3pz5jz42jfsfv2ly4npn3ty\"},{\"key\":\"module\",\"value\":\"ibc_channel\"},{\"key\":\"module\",\"value\":\"transfer\"}]},{\"type\":\"send_packet\",\"attributes\":[{\"key\":\"packet_data\",\"value\":\"{\\\"amount\\\":\\\"2000000000\\\",\\\"denom\\\":\\\"transfer/channel-26/xeth\\\",\\\"receiver\\\":\\\"sif19q2swhcxkxlc6va3pz5jz42jfsfv2ly4kuu8y0\\\",\\\"sender\\\":\\\"cosmos19q2swhcxkxlc6va3pz5jz42jfsfv2ly4npn3ty\\\"}\"},{\"key\":\"packet_timeout_height\",\"value\":\"1-2063887\"},{\"key\":\"packet_timeout_timestamp\",\"value\":\"1631164712770712287\"},{\"key\":\"packet_sequence\",\"value\":\"69\"},{\"key\":\"packet_src_port\",\"value\":\"transfer\"},{\"key\":\"packet_src_channel\",\"value\":\"channel-26\"},{\"key\":\"packet_dst_port\",\"value\":\"transfer\"},{\"key\":\"packet_dst_channel\",\"value\":\"channel-114\"},{\"key\":\"packet_channel_ordering\",\"value\":\"ORDER_UNORDERED\"},{\"key\":\"packet_connection\",\"value\":\"connection-28\"}]},{\"type\":\"transfer\",\"attributes\":[{\"key\":\"recipient\",\"value\":\"cosmos1yl6hdjhmkf37639730gffanpzndzdpmhwlkfhr\"},{\"key\":\"sender\",\"value\":\"cosmos19q2swhcxkxlc6va3pz5jz42jfsfv2ly4npn3ty\"},{\"key\":\"amount\",\"value\":\"2000000000ibc/EAB7F58822348DDDA139B53062229470220170D7376FAAC5CEACD65BDA3347FA\"}]}]}]","logs":[{"msg_index":0,"log":"","events":[{"type":"ibc_transfer","attributes":[{"key":"sender","value":"cosmos19q2swhcxkxlc6va3pz5jz42jfsfv2ly4npn3ty"},{"key":"receiver","value":"sif19q2swhcxkxlc6va3pz5jz42jfsfv2ly4kuu8y0"}]},{"type":"message","attributes":[{"key":"action","value":"transfer"},{"key":"sender","value":"cosmos19q2swhcxkxlc6va3pz5jz42jfsfv2ly4npn3ty"},{"key":"module","value":"ibc_channel"},{"key":"module","value":"transfer"}]},{"type":"send_packet","attributes":[{"key":"packet_data","value":"{\"amount\":\"2000000000\",\"denom\":\"transfer/channel-26/xeth\",\"receiver\":\"sif19q2swhcxkxlc6va3pz5jz42jfsfv2ly4kuu8y0\",\"sender\":\"cosmos19q2swhcxkxlc6va3pz5jz42jfsfv2ly4npn3ty\"}"},{"key":"packet_timeout_height","value":"1-2063887"},{"key":"packet_timeout_timestamp","value":"1631164712770712287"},{"key":"packet_sequence","value":"69"},{"key":"packet_src_port","value":"transfer"},{"key":"packet_src_channel","value":"channel-26"},{"key":"packet_dst_port","value":"transfer"},{"key":"packet_dst_channel","value":"channel-114"},{"key":"packet_channel_ordering","value":"ORDER_UNORDERED"},{"key":"packet_connection","value":"connection-28"}]},{"type":"transfer","attributes":[{"key":"recipient","value":"cosmos1yl6hdjhmkf37639730gffanpzndzdpmhwlkfhr"},{"key":"sender","value":"cosmos19q2swhcxkxlc6va3pz5jz42jfsfv2ly4npn3ty"},{"key":"amount","value":"2000000000ibc/EAB7F58822348DDDA139B53062229470220170D7376FAAC5CEACD65BDA3347FA"}]}]}],"info":"","gas_wanted":"300000","gas_used":"125671","tx":null,"timestamp":""}
```

4.  Query balance on the cosmos. Note the balance was deducted properly

> gaiad query bank balances cosmos19q2swhcxkxlc6va3pz5jz42jfsfv2ly4npn3ty --node https://rpc.testnet.cosmos.network:443 --chain-id cosmoshub-testnet

```
balances:
- amount: "1000000000000"
  denom: ibc/11C219BAA2C8AF0862D6F77F1BD62DE59755D5EAAF3B33FE0CEAFADD2195328E
- amount: "500"
  denom: ibc/7E10CAD296837763B61CD8376EE9B1AD526FFF42BD61E99D1149F68CF044F6C5
- amount: "20000000000"
  denom: ibc/830D5C093E8D24CE25C1BFF5896B382589E07E37C316684F661A24E74B00B9A8
- amount: "28814542915"
  denom: ibc/EAB7F58822348DDDA139B53062229470220170D7376FAAC5CEACD65BDA3347FA
- amount: "100"
  denom: ibc/FEB745594AA528DDB2EB216943D81DB046308A47C07ACB96D58AB4D7B067EC1C
- amount: "989777177778"
  denom: uphoton
```

5. Query the balance on the sif side. Note the balance was not updated

> sifnoded query bank balances sif19q2swhcxkxlc6va3pz5jz42jfsfv2ly4kuu8y0 --node=tcp://rpc-devnet.sifchain.finance:80 --chain-id=sifchain-devnet-1 | grep eth -B 1

```
- amount: "7706325658500000000"
  denom: ceth
--
- amount: "0"
  denom: xeth
```

Also notice that after the timeout has passed, the funds are not given back to the source (cosmos)

**What tokens are you interacting with when this issue occurs?**
ceth (sifchain)
ibc/EAB7F58822348DDDA139B53062229470220170D7376FAAC5CEACD65BDA3347FA (cosmos)
