### ISSUE TITLE
Not able to transfer eth from sif to cosmos

### ISSUE THREAD

**Issue by pgoos** [Sifchain/sifnode#1847]
**Current behavior**
Eth assets are not transferred from sif (DevNet) to cosmos testnet and no refund is performed. Balance is deducted on the sif side but not updated on cosmos side. After timeout has reached, funds are not given back

**Expected behavior**
Eth assets are transferred from sif to cosmos. Balance is deducted on the sif side and is updated accordingly on the cosmos side.

**Steps to reproduce**
1. Query the balance on the sif side
> sifnoded query bank balances sif19q2swhcxkxlc6va3pz5jz42jfsfv2ly4kuu8y0 --node=tcp://rpc-devnet.sifchain.finance:80 --chain-id=sifchain-devnet-1 | grep eth -B 1

```
- amount: "7706325658500000000"
  denom: ceth
--
- amount: "0"
  denom: xeth
```
2. Query the balance on the cosmos side
> gaiad query bank balances cosmos19q2swhcxkxlc6va3pz5jz42jfsfv2ly4npn3ty --node https://rpc.testnet.cosmos.network:443 --chain-id cosmoshub-testnet

```
balances:
- amount: "1000000000000"
  denom: ibc/11C219BAA2C8AF0862D6F77F1BD62DE59755D5EAAF3B33FE0CEAFADD2195328E
- amount: "500"
  denom: ibc/7E10CAD296837763B61CD8376EE9B1AD526FFF42BD61E99D1149F68CF044F6C5
- amount: "20000000000"
  denom: ibc/830D5C093E8D24CE25C1BFF5896B382589E07E37C316684F661A24E74B00B9A8
- amount: "28814542915"
  denom: ibc/EAB7F58822348DDDA139B53062229470220170D7376FAAC5CEACD65BDA3347FA
- amount: "100"
  denom: ibc/FEB745594AA528DDB2EB216943D81DB046308A47C07ACB96D58AB4D7B067EC1C
- amount: "989777177778"
  denom: uphoton
```

Notice `denom: ibc/EAB7F58822348DDDA139B53062229470220170D7376FAAC5CEACD65BDA3347FA` in particular
3. Transfer eth funds from DevNet to cosmos with `sifnoded` CLI
> sifnoded tx ibc-transfer transfer transfer channel-114 cosmos19q2swhcxkxlc6va3pz5jz42jfsfv2ly4npn3ty 1581454341522453215ceth  --from sif19q2swhcxkxlc6va3pz5jz42jfsfv2ly4kuu8y0     --keyring-backend test     --node tcp://rpc-devnet.sifchain.finance:80 --chain-id sifchain-devnet-1     -y     --packet-timeout-timestamp 6000000000000 --gas 500000 --gas-prices 0.5rowan

```
{"height":"2069945","txhash":"025976AC00AC0ACB3D276EF81376F10142B5BC89A4676B848AB21312E96AD67F","codespace":"","code":0,"data":"0A0A0A087472616E73666572","raw_log":"[{\"events\":[{\"type\":\"converted_transfer\",\"attributes\":[{\"key\":\"module\",\"value\":\"scibctransfer\"},{\"key\":\"sent_amount\",\"value\":\"1581454341500000000\"},{\"key\":\"sent_denom\",\"value\":\"ceth\"},{\"key\":\"converted_amount\",\"value\":\"15814543415\"},{\"key\":\"converted_denom\",\"value\":\"xeth\"}]},{\"type\":\"ibc_transfer\",\"attributes\":[{\"key\":\"sender\",\"value\":\"sif19q2swhcxkxlc6va3pz5jz42jfsfv2ly4kuu8y0\"},{\"key\":\"receiver\",\"value\":\"cosmos19q2swhcxkxlc6va3pz5jz42jfsfv2ly4npn3ty\"}]},{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"transfer\"},{\"key\":\"sender\",\"value\":\"sif19q2swhcxkxlc6va3pz5jz42jfsfv2ly4kuu8y0\"},{\"key\":\"sender\",\"value\":\"sif1u8awp0rh8ml7rkj6huf3v5v7q4zwn76rqe57q4\"},{\"key\":\"sender\",\"value\":\"sif19q2swhcxkxlc6va3pz5jz42jfsfv2ly4kuu8y0\"},{\"key\":\"module\",\"value\":\"ibc_channel\"},{\"key\":\"module\",\"value\":\"transfer\"}]},{\"type\":\"send_packet\",\"attributes\":[{\"key\":\"packet_data\",\"value\":\"{\\\"amount\\\":\\\"15814543415\\\",\\\"denom\\\":\\\"xeth\\\",\\\"receiver\\\":\\\"cosmos19q2swhcxkxlc6va3pz5jz42jfsfv2ly4npn3ty\\\",\\\"sender\\\":\\\"sif19q2swhcxkxlc6va3pz5jz42jfsfv2ly4kuu8y0\\\"}\"},{\"key\":\"packet_timeout_height\",\"value\":\"0-355799\"},{\"key\":\"packet_timeout_timestamp\",\"value\":\"1631170096768636813\"},{\"key\":\"packet_sequence\",\"value\":\"34\"},{\"key\":\"packet_src_port\",\"value\":\"transfer\"},{\"key\":\"packet_src_channel\",\"value\":\"channel-114\"},{\"key\":\"packet_dst_port\",\"value\":\"transfer\"},{\"key\":\"packet_dst_channel\",\"value\":\"channel-26\"},{\"key\":\"packet_channel_ordering\",\"value\":\"ORDER_UNORDERED\"},{\"key\":\"packet_connection\",\"value\":\"connection-125\"}]},{\"type\":\"transfer\",\"attributes\":[{\"key\":\"recipient\",\"value\":\"sif1ts6nhhr7z93umz4vdlqvrzxm6xwx3qjy22qex7\"},{\"key\":\"sender\",\"value\":\"sif19q2swhcxkxlc6va3pz5jz42jfsfv2ly4kuu8y0\"},{\"key\":\"amount\",\"value\":\"1581454341500000000ceth\"},{\"key\":\"recipient\",\"value\":\"sif19q2swhcxkxlc6va3pz5jz42jfsfv2ly4kuu8y0\"},{\"key\":\"sender\",\"value\":\"sif1u8awp0rh8ml7rkj6huf3v5v7q4zwn76rqe57q4\"},{\"key\":\"amount\",\"value\":\"15814543415xeth\"},{\"key\":\"recipient\",\"value\":\"sif1jf7gw9ca4wdzejeyflcflx0sgrk04rvahaxj9v\"},{\"key\":\"sender\",\"value\":\"sif19q2swhcxkxlc6va3pz5jz42jfsfv2ly4kuu8y0\"},{\"key\":\"amount\",\"value\":\"15814543415xeth\"}]}]}]","logs":[{"msg_index":0,"log":"","events":[{"type":"converted_transfer","attributes":[{"key":"module","value":"scibctransfer"},{"key":"sent_amount","value":"1581454341500000000"},{"key":"sent_denom","value":"ceth"},{"key":"converted_amount","value":"15814543415"},{"key":"converted_denom","value":"xeth"}]},{"type":"ibc_transfer","attributes":[{"key":"sender","value":"sif19q2swhcxkxlc6va3pz5jz42jfsfv2ly4kuu8y0"},{"key":"receiver","value":"cosmos19q2swhcxkxlc6va3pz5jz42jfsfv2ly4npn3ty"}]},{"type":"message","attributes":[{"key":"action","value":"transfer"},{"key":"sender","value":"sif19q2swhcxkxlc6va3pz5jz42jfsfv2ly4kuu8y0"},{"key":"sender","value":"sif1u8awp0rh8ml7rkj6huf3v5v7q4zwn76rqe57q4"},{"key":"sender","value":"sif19q2swhcxkxlc6va3pz5jz42jfsfv2ly4kuu8y0"},{"key":"module","value":"ibc_channel"},{"key":"module","value":"transfer"}]},{"type":"send_packet","attributes":[{"key":"packet_data","value":"{\"amount\":\"15814543415\",\"denom\":\"xeth\",\"receiver\":\"cosmos19q2swhcxkxlc6va3pz5jz42jfsfv2ly4npn3ty\",\"sender\":\"sif19q2swhcxkxlc6va3pz5jz42jfsfv2ly4kuu8y0\"}"},{"key":"packet_timeout_height","value":"0-355799"},{"key":"packet_timeout_timestamp","value":"1631170096768636813"},{"key":"packet_sequence","value":"34"},{"key":"packet_src_port","value":"transfer"},{"key":"packet_src_channel","value":"channel-114"},{"key":"packet_dst_port","value":"transfer"},{"key":"packet_dst_channel","value":"channel-26"},{"key":"packet_channel_ordering","value":"ORDER_UNORDERED"},{"key":"packet_connection","value":"connection-125"}]},{"type":"transfer","attributes":[{"key":"recipient","value":"sif1ts6nhhr7z93umz4vdlqvrzxm6xwx3qjy22qex7"},{"key":"sender","value":"sif19q2swhcxkxlc6va3pz5jz42jfsfv2ly4kuu8y0"},{"key":"amount","value":"1581454341500000000ceth"},{"key":"recipient","value":"sif19q2swhcxkxlc6va3pz5jz42jfsfv2ly4kuu8y0"},{"key":"sender","value":"sif1u8awp0rh8ml7rkj6huf3v5v7q4zwn76rqe57q4"},{"key":"amount","value":"15814543415xeth"},{"key":"recipient","value":"sif1jf7gw9ca4wdzejeyflcflx0sgrk04rvahaxj9v"},{"key":"sender","value":"sif19q2swhcxkxlc6va3pz5jz42jfsfv2ly4kuu8y0"},{"key":"amount","value":"15814543415xeth"}]}]}],"info":"","gas_wanted":"500000","gas_used":"261100","tx":null,"timestamp":""}
```

4. Query the balance on the sif side. Notice the balance is correctly deducted.
> sifnoded query bank balances sif19q2swhcxkxlc6va3pz5jz42jfsfv2ly4kuu8y0 --node=tcp://rpc-devnet.sifchain.finance:80 --chain-id=sifchain-devnet-1 | grep eth -B 1

```
- amount: "6124871317000000000"
  denom: ceth
--
- amount: "0"
  denom: xeth
```

5. Query the balance on the cosmos side. Notice the balance is not updated as expected.
> gaiad query bank balances cosmos19q2swhcxkxlc6va3pz5jz42jfsfv2ly4npn3ty --node https://rpc.testnet.cosmos.network:443 --chain-id cosmoshub-testnet

```
balances:
- amount: "1000000000000"
  denom: ibc/11C219BAA2C8AF0862D6F77F1BD62DE59755D5EAAF3B33FE0CEAFADD2195328E
- amount: "500"
  denom: ibc/7E10CAD296837763B61CD8376EE9B1AD526FFF42BD61E99D1149F68CF044F6C5
- amount: "20000000000"
  denom: ibc/830D5C093E8D24CE25C1BFF5896B382589E07E37C316684F661A24E74B00B9A8
- amount: "28814542915"
  denom: ibc/EAB7F58822348DDDA139B53062229470220170D7376FAAC5CEACD65BDA3347FA
- amount: "100"
  denom: ibc/FEB745594AA528DDB2EB216943D81DB046308A47C07ACB96D58AB4D7B067EC1C
- amount: "989777177778"
  denom: uphoton
```

Additionally notice, that after timeout has passed, no refund is performed and assets are lost.

**What tokens are you interacting with when this issue occurs?**
ceth (sifchain)
ibc/EAB7F58822348DDDA139B53062229470220170D7376FAAC5CEACD65BDA3347FA (cosmos)
