### ISSUE TITLE
[Peggy] Relayers / Validators out of gas issue

### ISSUE THREAD

**Issue by utx0** [Sifchain/sifnode#254]
Description:

When a transaction passes from Ethereum to Sifchain via the [ebrelayer](https://github.com/Sifchain/sifnode/tree/develop/cmd/ebrelayer), the relayer reports an out of gas error:

```
❯ sifnodecli q tx 4A6710512C8D506155F59600F870592ED6BAED74116F6718E6F83DAC6D43FD2F
height: 29443
txhash: 4A6710512C8D506155F59600F870592ED6BAED74116F6718E6F83DAC6D43FD2F
codespace: sdk
code: 11
data: ""
rawlog: 'out of gas: out of gas in location: ReadFlat; gasWanted: 200000, gasUsed: 200706'
logs: []
info: ""
gaswanted: 200000
gasused: 200706
```

Version:

```
name: sifchain
server_name: sifnoded
client_name: sifnodecli
version: 0.0.1
commit: 62a7d9d2790153c22fda084357993d4a03daf2fc
build_tags: ""
go: go version go1.15.3 linux/amd64
```

Expected Behaviour:

That the new token be minted accordingly and deposited to the destination address.

Additional Information:

The validator in question has/had plenty of tokens available to cover gas:

```
coins:
  - denom: chot
    amount: "10000000000000000000000000000000000"
  - denom: clink
    amount: "10000000000000000000000000000000000"
  - denom: cusdc
    amount: "10000000000000000000000000000000000"
  - denom: cusdt
    amount: "10000000000000000000000000000000000"
  - denom: rowan
    amount: "9999999999995000000000"
```
