### ISSUE TITLE
Unable to fetch all balances for a sif account with large number of denoms

### ISSUE THREAD

**Issue by jzvikart** [Sifchain/sifnode#2858]
To reproduce:
1. Create a sif wallet with 100000 denoms. For some reason, it is important that you create it with tokens coming from Ethereum, not from genesis.
2. `sifnoded query bank balances --offset 99999 --limit 1`

Result:
```
Error: post failed: Post "http://localhost:26657": EOF
```

Expected result: something like
```
balances:
- amount: "123456"
  denom: sifBridge99990x0002273068a986d63f0367f4cab49c1aaf1e3595
pagination:
  next_key: c2lmQnJpZGdlOTk5OTB4MDAwMjMzZDg2NDA2ZTJmYjg3M2MxZjNjYzllODFhZWVlYzE1NDFlOQ==
  total: "0"
```

Differential diagnosis: `sifnoded query bank balances --limit 1 --offset 1` works OK.

Related issues:
- #2520
- #2794
