### ISSUE TITLE
endpoint to retrieve lppd params

### ISSUE THREAD

**Issue by pgoos** [Sifchain/sifnode#3190]
We need to have an endpoint (equivalent of the same for reward params, i.e. http://sifchain.testnet.sifchain.finance:1317/clp/getRewardParams) to retrieve current settings of LPPD policy. Similar of what is achieved through CLI:
```
+ sifnoded q clp lppd-params --node http://sifchain.testnet.sifchain.finance:26657 --chain-id sifchain-testnet-1
params:
  distribution_periods:
  - distribution_period_block_rate: "0.000488020685100000"
    distribution_period_end_block: "93700"
    distribution_period_mod: "1"
    distribution_period_start_block: "93600"
```

That would help DS to effectively analyze block data knowing if the policy is activated or not.
